version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: socapp
      MYSQL_USER: monty
      MYSQL_PASSWORD: debian1
      MYSQL_ROOT_PASSWORD: p@ssworb
    ports:
      - '3306:3306'
    expose:
      - '3306'

