version: '2'

services:
#  mysql:
#    image: mysql
#    container_name: mysql
#    environment:
#      MYSQL_DATABASE: socapp
#      MYSQL_USER: monty
#      MYSQL_PASSWORD: debian1
#      MYSQL_ROOT_PASSWORD: p@ssworb
#    networks:
#      - flask_net
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'

  soc-app:
    image: soc-app
    container_name: socapp
    environment:
      FLASK_APP: wsgi
    networks:
      - flask_net
    ports:
      - '5000:5000'

  nginx:
    image: socnginx
    container_name: socnginx
    networks:
      - flask_net
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - 'soc-app'
    expose:
      - '443'
      - '80'

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - flask_net
    ports:
      - '6379:6379'
    expose:
      - '6379'

networks:
  flask_net:
